In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm.auto import tqdm

tqdm.pandas()

%matplotlib inline

SEED = 42

NUM_FEATURES = 5000
NUM_CLASSES = 3993

train_features = pd.read_csv("../data/expanded/train_features.csv", names=range(NUM_FEATURES))
train_labels = pd.read_csv("../data/expanded/train_labels.csv", names=range(NUM_CLASSES))

validation_features = pd.read_csv("../data/expanded/dev_features.csv", names=range(NUM_FEATURES))
validation_labels = pd.read_csv("../data/expanded/dev_labels.csv", names=range(NUM_CLASSES))

C:\Users\Andrew\Anaconda3\lib\site-packages\tqdm\std.py:666: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel


Really large differences in max and variance:

In [9]:
np.sort(np.var(train_features, axis = 0))

array([7.39786264e-02, 8.58397490e-02, 1.23233068e-01, ...,
       3.89117787e+04, 4.50693076e+04, 5.87975513e+04])

In [10]:
np.sort(np.max(train_features, axis = 0))

array([2.88664600e+00, 3.75861900e+00, 3.79371000e+00, ...,
       2.28867539e+04, 2.43905879e+04, 2.63541699e+04])

Single feature prediction:

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X = train_features

rf = RandomForestClassifier(class_weight = 'balanced')
accuracy = np.zeros(NUM_CLASSES)
precision = np.zeros(NUM_CLASSES)

# for i in range(NUM_CLASSES):
for i in range(10):
    y = train_labels.iloc[:,i]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
    rf.fit(X_train,y_train)
    y_pred = rf.predict(X_test)
    accuracy[i] = (sum(y_pred == y_test)/len(y_test))
    
    if sum(y_test == 1) == 0:
        precision[i] = float('nan')
    else:
        precision[i] = (sum(np.logical_and(y_pred == y_test, y_pred == 1))/sum(y_test == 1))

In [12]:
precision

array([       nan, 0.31578947, 0.        , ..., 0.        , 0.        ,
       0.        ])